#### Familiarizing with Pandas library

* Read the dataset into a pandas dataframe and explore various pandas functions over that data.
* Majorly focus on
    * Multi-indexing
    * Concat and Append
    * Merge and Joins

In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("./telco_customer_churn.csv")
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
data.shape

(7043, 21)

In [10]:
data[data['gender'] == 'Male']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7033,9767-FFLEM,Male,0,No,No,38,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),69.50,2625.25,No
7035,8456-QDAVC,Male,0,No,No,19,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.1,No
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
data[:6]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes

In [12]:
data[['SeniorCitizen', 'Partner', 'Dependents', 'InternetService']]

      SeniorCitizen Partner Dependents InternetService
0                 0     Yes         No             DSL
1                 0      No         No             DSL
2                 0      No         No             DSL
3                 0      No         No             DSL
4                 0      No         No     Fiber optic
...             ...     ...        ...             ...
7038              0     Yes        Yes             DSL
7039              0     Yes        Yes     Fiber optic
7040              0     Yes        Yes             DSL
7041              1     Yes         No     Fiber optic
7042              0      No         No     Fiber optic

[7043 rows x 4 columns]

In [14]:
idx = pd.IndexSlice
data.loc[idx[:25], idx[:'tenure']]

    customerID  gender  SeniorCitizen Partner Dependents  tenure
0   7590-VHVEG  Female              0     Yes         No       1
1   5575-GNVDE    Male              0      No         No      34
2   3668-QPYBK    Male              0      No         No       2
3   7795-CFOCW    Male              0      No         No      45
4   9237-HQITU  Female              0      No         No       2
5   9305-CDSKC  Female              0      No         No       8
6   1452-KIOVK    Male              0      No        Yes      22
7   6713-OKOMC  Female              0      No         No      10
8   7892-POOKP  Female              0     Yes         No      28
9   6388-TABGU    Male              0      No        Yes      62
10  9763-GRSKD    Male              0     Yes        Yes      13
11  7469-LKBCI    Male              0      No         No      16
12  8091-TTVAX    Male              0     Yes         No      58
13  0280-XJGEX    Male              0      No         No      49
14  5129-JLPIS    Male              0      No         No      25
15  3655-SNQYZ  Female              0     Yes        Yes      69
16  8191-XWSZG  Female              0      No         No      52
17  9959-WOFKT    Male              0      No        Yes      71
18  4190-MFLUW  Female              0     Yes        Yes      10
19  4183-MYFRB  Female              0      No         No      21
20  8779-QRDMV    Male              1      No         No       1
21  1680-VDCWW    Male              0     Yes         No      12
22  1066-JKSGK    Male              0      No         No       1
23  3638-WEABW  Female              0     Yes         No      58
24  6322-HRPFA    Male              0     Yes        Yes      49
25  6865-JZNKO  Female              0      No         No      30

In [23]:
data.loc[(:250), ('PaymentMethod':'TotalCharges')]

SyntaxError: invalid syntax (<ipython-input-23-e72c6c55d44a>, line 1)

In [26]:
df1 = pd.read_csv("./20190928-items.csv")
df1

,asin,brand,title,url,image,rating,reviewUrl,totalReviews,prices
0,B0000SX2UC,Nokia,Dual-Band / Tri-Mode Sprint PCS Phone w/ Voice...,https://www.amazon.com/Dual-Band-Tri-Mode-Acti...,https://m.media-amazon.com/images/I/2143EBQ210...,3.0,https://www.amazon.com/product-reviews/B0000SX2UC,14,NaN
1,B0009N5L7K,Motorola,Motorola I265 phone,https://www.amazon.com/Motorola-i265-I265-phon...,https://m.media-amazon.com/images/I/419WBAVDAR...,2.9,https://www.amazon.com/product-reviews/B0009N5L7K,7,$49.95
2,B000SKTZ0S,Motorola,MOTOROLA C168i AT&T CINGULAR PREPAID GOPHONE C...,https://www.amazon.com/MOTOROLA-C168i-CINGULAR...,https://m.media-amazon.com/images/I/71b+q3ydkI...,2.6,https://www.amazon.com/product-reviews/B000SKTZ0S,22,NaN
3,B00198M12M,Nokia,Nokia 6500 Slide Black/silver Unlocked Cell Phone,https://www.amazon.com/Nokia-6500-Slide-silver...,https://m.media-amazon.com/images/I/41ss4HpLkL...,2.4,https://www.amazon.com/product-reviews/B00198M12M,5,NaN
4,B001AO4OUC,Motorola,Motorola i335 Cell Phone Boost Mobile,https://www.amazon.com/Motorola-i335-Phone-Boo...,https://m.media-amazon.com/images/I/710UO8gdT+...,3.3,https://www.amazon.com/product-reviews/B001AO4OUC,21,NaN
...,...,...,...,...,...,...,...,...,...
787,B07WFJ6HRF,Apple,"Apple iPhone XS, 512GB, Gold - For Verizon (Re...",https://www.amazon.com/Apple-iPhone-XS-512GB-G...,https://m.media-amazon.com/images/I/71kt40Gjzt...,3.7,https://www.amazon.com/product-reviews/B07WFJ6HRF,50,"$999.95,$1,349.99"
788,B07WKSVF6X,Samsung,"Samsung Galaxy A50 128GB, 4GB RAM 6.4"" Display...",https://www.amazon.com/Samsung-A50-Display-Fac...,https://m.media-amazon.com/images/I/61HyCNLJ2+...,4.7,https://www.amazon.com/product-reviews/B07WKSVF6X,7,$304.99
789,B07WVRJQ7V,Samsung,"Samsung Galaxy S9 (64GB, 4GB RAM) 5.8"" QHD+ Di...",https://www.amazon.com/Samsung-Galaxy-S9-Displ...,https://m.media-amazon.com/images/I/71EpwFTgLO...,2.0,https://www.amazon.com/product-reviews/B07WVRJQ7V,1,$519.99
790,B07WXKWDT2,Motorola,"Motorola Moto G7 Play (32GB, 2GB RAM) 5.7"" HD+...",https://www.amazon.com/Motorola-Vision-Display...,https://m.media-amazon.com/images/I/51xgfG4A28...,3.0,https://www.amazon.com/product-reviews/B07WXKWDT2,5,$139.99
791,B07X51T2VK,HUAWEI,"Honor 5X Unlocked Smartphone, 16GB Dark Grey (...",https://www.amazon.com/Honor-Unlocked-Smartpho...,https://m.media-amazon.com/images/I/71qG253Lcx...,4.0,https://www.amazon.com/product-reviews/B07X51T2VK,1,$74.99

In [27]:
df2 = pd.read_csv("./20190928-reviews.csv")
df2

,asin,name,rating,date,verified,title,body,helpfulVotes
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0
...,...,...,...,...,...,...,...,...
82810,B07WXKWDT2,Prabhakaran,5,"September 24, 2019",True,International version. Will require USA adapte...,Best phone at this price.,NaN
82811,B07WXKWDT2,rvwonder,3,"September 17, 2019",False,Be careful of International Version if Using T...,If you intend to use this phone on T Mobile be...,NaN
82812,B07WXKWDT2,markw707,1,"September 8, 2019",False,Moto G7 Play Freezes Every Time I Use It.,Here is my Moto G7 Play complaint: It freezes ...,NaN
82813,B07WXKWDT2,Amazon Customer,1,"September 13, 2019",False,Camera is not good,As far as function works great camera no go wo...,NaN
82814,B07X51T2VK,Steve H.,4,"September 16, 2019",True,Awesome.,"What a great phone! Sleek, fast, great soundin...",1.0

In [41]:
df3 = pd.merge(df2, df1, how='outer')
df3

,asin,name,rating,date,verified,title,body,helpfulVotes,brand,url,image,reviewUrl,totalReviews,prices
0,B0000SX2UC,Janet,3.0,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,B0000SX2UC,Luke Wyatt,1.0,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0,NaN,NaN,NaN,NaN,NaN,NaN
2,B0000SX2UC,Brooke,5.0,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0,NaN,NaN,NaN,NaN,NaN,NaN
3,B0000SX2UC,amy m. teague,3.0,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,B0000SX2UC,tristazbimmer,4.0,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83602,B07WFJ6HRF,NaN,3.7,NaN,NaN,"Apple iPhone XS, 512GB, Gold - For Verizon (Re...",NaN,NaN,Apple,https://www.amazon.com/Apple-iPhone-XS-512GB-G...,https://m.media-amazon.com/images/I/71kt40Gjzt...,https://www.amazon.com/product-reviews/B07WFJ6HRF,50.0,"$999.95,$1,349.99"
83603,B07WKSVF6X,NaN,4.7,NaN,NaN,"Samsung Galaxy A50 128GB, 4GB RAM 6.4"" Display...",NaN,NaN,Samsung,https://www.amazon.com/Samsung-A50-Display-Fac...,https://m.media-amazon.com/images/I/61HyCNLJ2+...,https://www.amazon.com/product-reviews/B07WKSVF6X,7.0,$304.99
83604,B07WVRJQ7V,NaN,2.0,NaN,NaN,"Samsung Galaxy S9 (64GB, 4GB RAM) 5.8"" QHD+ Di...",NaN,NaN,Samsung,https://www.amazon.com/Samsung-Galaxy-S9-Displ...,https://m.media-amazon.com/images/I/71EpwFTgLO...,https://www.amazon.com/product-reviews/B07WVRJQ7V,1.0,$519.99
83605,B07WXKWDT2,NaN,3.0,NaN,NaN,"Motorola Moto G7 Play (32GB, 2GB RAM) 5.7"" HD+...",NaN,NaN,Motorola,https://www.amazon.com/Motorola-Vision-Display...,https://m.media-amazon.com/images/I/51xgfG4A28...,https://www.amazon.com/product-reviews/B07WXKWDT2,5.0,$139.99
83606,B07X51T2VK,NaN,4.0,NaN,NaN,"Honor 5X Unlocked Smartphone, 16GB Dark Grey (...",NaN,NaN,HUAWEI,https://www.amazon.com/Honor-Unlocked-Smartpho...,https://m.media-amazon.com/images/I/71qG253Lcx...,https://www.amazon.com/product-reviews/B07X51T2VK,1.0,$74.99

In [45]:
df4 = pd.merge(df2, df1, on="asin")

In [37]:
pd.concat([df2,df1])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,asin,body,brand,date,helpfulVotes,image,name,prices,rating,reviewUrl,title,totalReviews,url,verified
0,B0000SX2UC,I had the Samsung A600 for awhile which is abs...,NaN,"October 11, 2005",1.0,NaN,Janet,NaN,3.0,NaN,"Def not best, but not worst",NaN,NaN,False
1,B0000SX2UC,Due to a software issue between Nokia and Spri...,NaN,"January 7, 2004",17.0,NaN,Luke Wyatt,NaN,1.0,NaN,Text Messaging Doesn't Work,NaN,NaN,False
2,B0000SX2UC,"This is a great, reliable phone. I also purcha...",NaN,"December 30, 2003",5.0,NaN,Brooke,NaN,5.0,NaN,Love This Phone,NaN,NaN,False
3,B0000SX2UC,"I love the phone and all, because I really did...",NaN,"March 18, 2004",1.0,NaN,amy m. teague,NaN,3.0,NaN,"Love the Phone, BUT...!",NaN,NaN,False
4,B0000SX2UC,The phone has been great for every purpose it ...,NaN,"August 28, 2005",1.0,NaN,tristazbimmer,NaN,4.0,NaN,"Great phone service and options, lousy case!",NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,B07WFJ6HRF,NaN,Apple,NaN,NaN,https://m.media-amazon.com/images/I/71kt40Gjzt...,NaN,"$999.95,$1,349.99",3.7,https://www.amazon.com/product-reviews/B07WFJ6HRF,"Apple iPhone XS, 512GB, Gold - For Verizon (Re...",50.0,https://www.amazon.com/Apple-iPhone-XS-512GB-G...,NaN
788,B07WKSVF6X,NaN,Samsung,NaN,NaN,https://m.media-amazon.com/images/I/61HyCNLJ2+...,NaN,$304.99,4.7,https://www.amazon.com/product-reviews/B07WKSVF6X,"Samsung Galaxy A50 128GB, 4GB RAM 6.4"" Display...",7.0,https://www.amazon.com/Samsung-A50-Display-Fac...,NaN
789,B07WVRJQ7V,NaN,Samsung,NaN,NaN,https://m.media-amazon.com/images/I/71EpwFTgLO...,NaN,$519.99,2.0,https://www.amazon.com/product-reviews/B07WVRJQ7V,"Samsung Galaxy S9 (64GB, 4GB RAM) 5.8"" QHD+ Di...",1.0,https://www.amazon.com/Samsung-Galaxy-S9-Displ...,NaN
790,B07WXKWDT2,NaN,Motorola,NaN,NaN,https://m.media-amazon.com/images/I/51xgfG4A28...,NaN,$139.99,3.0,https://www.amazon.com/product-reviews/B07WXKWDT2,"Motorola Moto G7 Play (32GB, 2GB RAM) 5.7"" HD+...",5.0,https://www.amazon.com/Motorola-Vision-Display...,NaN
791,B07X51T2VK,NaN,HUAWEI,NaN,NaN,https://m.media-amazon.com/images/I/71qG253Lcx...,NaN,$74.99,4.0,https://www.amazon.com/product-reviews/B07X51T2VK,"Honor 5X Unlocked Smartphone, 16GB Dark Grey (...",1.0,https://www.amazon.com/Honor-Unlocked-Smartpho...,NaN

In [32]:
df2.append(df1)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

,asin,body,brand,date,helpfulVotes,image,name,prices,rating,reviewUrl,title,totalReviews,url,verified
0,B0000SX2UC,I had the Samsung A600 for awhile which is abs...,NaN,"October 11, 2005",1.0,NaN,Janet,NaN,3.0,NaN,"Def not best, but not worst",NaN,NaN,False
1,B0000SX2UC,Due to a software issue between Nokia and Spri...,NaN,"January 7, 2004",17.0,NaN,Luke Wyatt,NaN,1.0,NaN,Text Messaging Doesn't Work,NaN,NaN,False
2,B0000SX2UC,"This is a great, reliable phone. I also purcha...",NaN,"December 30, 2003",5.0,NaN,Brooke,NaN,5.0,NaN,Love This Phone,NaN,NaN,False
3,B0000SX2UC,"I love the phone and all, because I really did...",NaN,"March 18, 2004",1.0,NaN,amy m. teague,NaN,3.0,NaN,"Love the Phone, BUT...!",NaN,NaN,False
4,B0000SX2UC,The phone has been great for every purpose it ...,NaN,"August 28, 2005",1.0,NaN,tristazbimmer,NaN,4.0,NaN,"Great phone service and options, lousy case!",NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,B07WFJ6HRF,NaN,Apple,NaN,NaN,https://m.media-amazon.com/images/I/71kt40Gjzt...,NaN,"$999.95,$1,349.99",3.7,https://www.amazon.com/product-reviews/B07WFJ6HRF,"Apple iPhone XS, 512GB, Gold - For Verizon (Re...",50.0,https://www.amazon.com/Apple-iPhone-XS-512GB-G...,NaN
788,B07WKSVF6X,NaN,Samsung,NaN,NaN,https://m.media-amazon.com/images/I/61HyCNLJ2+...,NaN,$304.99,4.7,https://www.amazon.com/product-reviews/B07WKSVF6X,"Samsung Galaxy A50 128GB, 4GB RAM 6.4"" Display...",7.0,https://www.amazon.com/Samsung-A50-Display-Fac...,NaN
789,B07WVRJQ7V,NaN,Samsung,NaN,NaN,https://m.media-amazon.com/images/I/71EpwFTgLO...,NaN,$519.99,2.0,https://www.amazon.com/product-reviews/B07WVRJQ7V,"Samsung Galaxy S9 (64GB, 4GB RAM) 5.8"" QHD+ Di...",1.0,https://www.amazon.com/Samsung-Galaxy-S9-Displ...,NaN
790,B07WXKWDT2,NaN,Motorola,NaN,NaN,https://m.media-amazon.com/images/I/51xgfG4A28...,NaN,$139.99,3.0,https://www.amazon.com/product-reviews/B07WXKWDT2,"Motorola Moto G7 Play (32GB, 2GB RAM) 5.7"" HD+...",5.0,https://www.amazon.com/Motorola-Vision-Display...,NaN
791,B07X51T2VK,NaN,HUAWEI,NaN,NaN,https://m.media-amazon.com/images/I/71qG253Lcx...,NaN,$74.99,4.0,https://www.amazon.com/product-reviews/B07X51T2VK,"Honor 5X Unlocked Smartphone, 16GB Dark Grey (...",1.0,https://www.amazon.com/Honor-Unlocked-Smartpho...,NaN